#!/bin/bash

echo "Building v4l2rtspserver snapshot tools with multi-device support..."

# Build device inspector utility with enhanced multi-device testing
echo "Building device_inspector with multi-device testing capabilities..."
if g++ -o device_inspector src/device_inspector.cpp -std=c++11; then
    echo "✓ device_inspector built successfully"
else
    echo "✗ Failed to build device_inspector"
    exit 1
fi

# Make it executable
chmod +x device_inspector

echo ""
echo "Tools built successfully!"
echo ""
echo "=========================================="
echo "DEVICE INSPECTOR USAGE"
echo "=========================================="
echo ""
echo "Basic Commands:"
echo "  ./device_inspector                       - Scan all video devices + auto group analysis"
echo "  ./device_inspector /dev/video0           - Inspect specific device + auto multi-device test"
echo "  ./device_inspector /dev/video0 --multi   - Comprehensive multi-device testing"
echo "  ./device_inspector /dev/video0 -m        - Same as --multi (short form)"
echo ""
echo "Multi-Device Testing Features:"
echo "  ✓ Concurrent device access testing"
echo "  ✓ Multi-format configuration testing (H264 + MJPEG)"
echo "  ✓ Device group compatibility analysis"
echo "  ✓ Optimal configuration recommendations"
echo "  ✓ Automatic related device discovery"
echo ""
echo "This tool will help determine:"
echo "  - Available video devices and capabilities"
echo "  - Supported formats (H264, MJPEG, YUYV, etc.)"
echo "  - Multiple simultaneous connection support"
echo "  - Concurrent format configuration capability"
echo "  - Best device pairing for H264 streaming + JPEG snapshots"
echo "  - Related devices from same physical camera"
echo ""
echo "Example Multi-Device Scenario:"
echo "  Camera creates /dev/video0 and /dev/video1"
echo "  → /dev/video0: H264 1920x1080 (main stream)"
echo "  → /dev/video1: MJPEG 640x480 (snapshots)"
echo "  → Optimal for v4l2rtspserver with real JPEG snapshots"
echo ""
echo "Recommended Testing Sequence:"
echo "  1. ./device_inspector                    # Scan all devices"
echo "  2. ./device_inspector /dev/video0 -m    # Deep analysis of primary device"
echo "  3. Follow configuration recommendations from output"
echo ""

echo "NEW SNAPSHOT FEATURES (v4l2rtspserver -j)"
echo "=========================================="
echo ""
echo "Enhanced Snapshot Modes:"
echo "  1. MJPEG Stream    - Real JPEG images when camera uses MJPEG format"
echo "  2. MJPEG Device    - Real JPEG images from separate /dev/videoN device"  
echo "  3. H264 MP4        - Mini MP4 videos with H264 keyframes (NEW!)"
echo "  4. H264_FALLBACK - Real MP4 snapshots with cached I-frames"
echo "     - Creates MP4 containers with actual H264 keyframes"
echo "     - Caches last I-frame and SPS/PPS data for reuse"
echo "     - Uses cached data when no current frame available"
echo "  5. YUV Converted   - Real JPEG images converted from YUV/RAW data"
echo ""
echo "Configuration Options:"
echo "  -j                 - Enable snapshots"
echo "  -J <w>x<h>         - Set MJPEG snapshot resolution (default 640x480)"
echo "  Examples: -J 320x240 (smaller), -J 1280x720 (HD)"
echo ""
echo "Smart Mode Selection:"
echo "  • Automatically detects camera capabilities"
echo "  • Prefers real images over fallback graphics"
echo "  • Uses H264 MP4 mode when SPS/PPS available"
echo "  • Falls back gracefully for limited cameras"
echo ""
echo "Endpoint: http://localhost:8554/snapshot"
echo "Returns: image/jpeg, video/mp4, or image/png (auto-detected)"
echo ""
echo "FFmpeg Compatibility:"
echo "  For better FFmpeg decoding, use: v4l2rtspserver -c (disables SPS/PPS repetition)"
echo "  Recommended: v4l2rtspserver -c -j /dev/video0 (optimal for most clients)" 