name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: build
      run: | 
          cmake .
          make
          
    - name: cpack
      run: | 
          cpack
          echo "artifactPath=$(ls *.deb)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.artifactPath }}
        path: ${{ env.artifactPath }}    